[general]
titleIconUrl = "https://cdn-icons-png.flaticon.com/512/3050/3050159.png"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
